FROM public.ecr.aws/lambda/python:3.8 as base
# requirements
RUN pip install poetry 
COPY pyproject.toml poetry.lock ./
RUN poetry export --output ./requirements.txt \
    && pip install -r ./requirements.txt --target ${LAMBDA_TASK_ROOT}
# application code
COPY endpoint ${LAMBDA_TASK_ROOT}
# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "endpoint/upload_model.lambda_handler" ]
