FROM ubuntu:22.04
RUN apt-get update && apt-get install -y \
    software-properties-common
RUN add-apt-repository universe
RUN apt-get update && apt-get install -y \
    python3.9 \
    python3-pip

RUN pip3 install poetry
RUN apt install -y npm
RUN npm install -g aws-cdk
COPY pyproject.toml poetry.lock /
RUN poetry install
COPY infrastructure cdk.json /

ENTRYPOINT ["poetry", "run"]
CMD ["cdk", "synth"]